---
- name: Configure Firewall on Ubuntu and CentOS
  hosts: all
  become: yes

  tasks:
    - name: Install UFW on Ubuntu
      apt:
        name: ufw
        state: present
      when: ansible_os_family == "Debian"

    - name: Allow SSH on UFW (Ubuntu)
      ufw:
        rule: allow
        name: OpenSSH
      when: ansible_os_family == "Debian"

    - name: Enable UFW (Ubuntu)
      ufw:
        state: enabled
      when: ansible_os_family == "Debian"
    - name: Install firewalld on CentOS
      yum:
        name: firewalld
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable firewalld (CentOS)
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Allow SSH through firewalld (CentOS)
      firewalld:
        service: ssh
        permanent: true
        state: enabled
        immediate: yes
      when: ansible_os_family == "RedHat"
